// Icon set powered by Phosphor Icons (https://phosphoricons.com)
// Each app-facing name maps to the best-fit Phosphor glyph.
import {
  SquaresFour,
  Plus,
  Wallet,
  Gear,
  TrendUp,
  TrendDown,
  Bank,
  CurrencyBtc,
  Globe,
  Trash,
  Flame,
  Eye,
  EyeSlash,
  CaretRight,
  ShieldCheck,
  Bell,
  DeviceMobile,
  DownloadSimple,
  UploadSimple,
  Star,
  Envelope,
  Moon,
  LockKey,
  Cloud,
  Sparkle,
  Diamond,
  ArrowsLeftRight,
  CaretDown,
  ArrowLeft,
  CalendarBlank,
  ClockCounterClockwise,
  ArrowDownLeft,
  ArrowUpRight,
  ArrowUp,
  ArrowDown,
  Check,
  PencilSimple,
  ChartBar,
  Fingerprint,
  Sun,
  ChatCircleText,
  Backspace,
  X
} from '@phosphor-icons/react';

export const Icons = {
  Dashboard: SquaresFour,
  Add: Plus,
  Wallet: Wallet,
  Settings: Gear,
  Trend: TrendUp,
  TrendDown: TrendDown,
  Bank: Bank,
  Crypto: CurrencyBtc,
  Global: Globe,
  Delete: Trash,
  Fire: Flame,
  Eye: Eye,
  EyeOff: EyeSlash,
  ChevronRight: CaretRight,
  Shield: ShieldCheck,
  Bell: Bell,
  Smartphone: DeviceMobile,
  Download: DownloadSimple,
  Upload: UploadSimple,
  Star: Star,
  Mail: Envelope,
  Moon: Moon,
  Lock: LockKey,
  Cloud: Cloud,
  Sparkles: Sparkle,
  Gem: Diamond,
  ArrowLeftRight: ArrowsLeftRight,
  ChevronDown: CaretDown,
  ArrowLeft: ArrowLeft,
  Calendar: CalendarBlank,
  History: ClockCounterClockwise,
  ArrowDownLeft: ArrowDownLeft,
  ArrowUpRight: ArrowUpRight,
  ArrowUp: ArrowUp,
  ArrowDown: ArrowDown,
  Check: Check,
  Edit: PencilSimple,
  BarChart: ChartBar,
  Fingerprint: Fingerprint,
  Sun: Sun,
  Feedback: ChatCircleText,
  Backspace: Backspace,
  Close: X
};
