import React from 'react';
import { 
  LayoutDashboard, 
  Plus, 
  Wallet, 
  Settings, 
  TrendingUp, 
  Landmark, 
  Bitcoin, 
  Globe,
  Trash2,
  Flame,
  Eye,
  EyeOff,
  ChevronRight,
  Shield,
  Bell,
  Smartphone,
  Download,
  Upload,
  Star,
  Mail,
  Moon,
  Lock,
  Cloud,
  Sparkles,
  Gem,
  ArrowLeftRight,
  ChevronDown,
  ArrowLeft,
  CalendarDays,
  History,
  ArrowDownLeft,
  ArrowUpRight,
  TrendingDown,
  ArrowUp,
  ArrowDown,
  Check,
  Edit2
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Add: Plus,
  Wallet: Wallet,
  Settings: Settings,
  Trend: TrendingUp,
  TrendDown: TrendingDown,
  Bank: Landmark,
  Crypto: Bitcoin,
  Global: Globe,
  Delete: Trash2,
  Fire: Flame,
  Eye: Eye,
  EyeOff: EyeOff,
  ChevronRight: ChevronRight,
  Shield: Shield,
  Bell: Bell,
  Smartphone: Smartphone,
  Download: Download,
  Upload: Upload,
  Star: Star,
  Mail: Mail,
  Moon: Moon,
  Lock: Lock,
  Cloud: Cloud,
  Sparkles: Sparkles,
  Gem: Gem,
  ArrowLeftRight: ArrowLeftRight,
  ChevronDown: ChevronDown,
  ArrowLeft: ArrowLeft,
  Calendar: CalendarDays,
  History: History,
  ArrowDownLeft: ArrowDownLeft,
  ArrowUpRight: ArrowUpRight,
  ArrowUp: ArrowUp,
  ArrowDown: ArrowDown,
  Check: Check,
  Edit: Edit2
};